[2024-12-01T16:56:43.876+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T16:56:27.372061+00:00 [queued]>
[2024-12-01T16:56:43.887+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T16:56:27.372061+00:00 [queued]>
[2024-12-01T16:56:43.887+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T16:56:43.887+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-12-01T16:56:43.887+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T16:56:43.902+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-12-01 16:56:27.372061+00:00
[2024-12-01T16:56:43.908+0000] {standard_task_runner.py:55} INFO - Started process 181 to run task
[2024-12-01T16:56:43.911+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2024-12-01T16:56:27.372061+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmp4owd0u64']
[2024-12-01T16:56:43.911+0000] {standard_task_runner.py:83} INFO - Job 227: Subtask tsk4
[2024-12-01T16:56:43.966+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2024-12-01T16:56:27.372061+00:00 [running]> on host d5758c87d718
[2024-12-01T16:56:44.038+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=marciothadeu1984@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-12-01T16:56:27.372061+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-01T16:56:27.372061+00:00
[2024-12-01T16:56:44.039+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-01T16:56:44.039+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-12-01T16:56:44.051+0000] {subprocess.py:86} INFO - Output:
[2024-12-01T16:56:44.054+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-01T16:56:44.065+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-01T16:56:44.069+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=email_test, task_id=tsk4, execution_date=20241201T165627, start_date=20241201T165643, end_date=20241201T165644
[2024-12-01T16:56:44.087+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-12-01T16:56:44.087+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2024-12-01T16:56:44.087+0000] {email.py:268} INFO - Email alerting: attempt 1
[2024-12-01T16:56:44.095+0000] {configuration.py:663} WARNING - section/key [smtp/smtp_user] not found in config
[2024-12-01T16:56:44.095+0000] {email.py:268} INFO - Email alerting: attempt 1
[2024-12-01T16:56:44.096+0000] {taskinstance.py:1831} ERROR - Failed to send email to: ['marciothadeu1984@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1520, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1581, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2231, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1829, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2233, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 91, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 152, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 270, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-12-01T16:56:44.116+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 227 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 181)
[2024-12-01T16:56:44.122+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-01T16:56:44.152+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
