[2024-11-23T16:32:34.989+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2024-11-23T16:32:34.310436+00:00 [queued]>
[2024-11-23T16:32:35.002+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2024-11-23T16:32:34.310436+00:00 [queued]>
[2024-11-23T16:32:35.002+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-23T16:32:35.002+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-11-23T16:32:35.002+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-23T16:32:35.022+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-11-23 16:32:34.310436+00:00
[2024-11-23T16:32:35.026+0000] {standard_task_runner.py:55} INFO - Started process 21248 to run task
[2024-11-23T16:32:35.029+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag2', 'tsk1', 'manual__2024-11-23T16:32:34.310436+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag2.py', '--cfg-path', '/tmp/tmp3f4k38uh']
[2024-11-23T16:32:35.030+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask tsk1
[2024-11-23T16:32:35.093+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag2.tsk1 manual__2024-11-23T16:32:34.310436+00:00 [running]> on host 6b6513c1cd28
[2024-11-23T16:32:35.177+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-11-23T16:32:34.310436+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-23T16:32:34.310436+00:00
[2024-11-23T16:32:35.178+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-11-23T16:32:35.179+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-11-23T16:32:35.189+0000] {subprocess.py:86} INFO - Output:
[2024-11-23T16:32:35.192+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-23T16:32:35.203+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-23T16:32:35.209+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag2, task_id=tsk1, execution_date=20241123T163234, start_date=20241123T163234, end_date=20241123T163235
[2024-11-23T16:32:35.224+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 42 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 21248)
[2024-11-23T16:32:35.240+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-23T16:32:35.266+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
