[2024-12-01T00:26:39.522+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T00:26:34.319017+00:00 [queued]>
[2024-12-01T00:26:39.533+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T00:26:34.319017+00:00 [queued]>
[2024-12-01T00:26:39.533+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T00:26:39.533+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-01T00:26:39.533+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T00:26:39.549+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-12-01 00:26:34.319017+00:00
[2024-12-01T00:26:39.555+0000] {standard_task_runner.py:55} INFO - Started process 2289 to run task
[2024-12-01T00:26:39.558+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2024-12-01T00:26:34.319017+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpqgl_8a7t']
[2024-12-01T00:26:39.558+0000] {standard_task_runner.py:83} INFO - Job 123: Subtask tsk4
[2024-12-01T00:26:39.616+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2024-12-01T00:26:34.319017+00:00 [running]> on host 4cf74f991bab
[2024-12-01T00:26:39.685+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=aws@evoluth.com.br
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-12-01T00:26:34.319017+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-01T00:26:34.319017+00:00
[2024-12-01T00:26:39.686+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-01T00:26:39.687+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-12-01T00:26:39.701+0000] {subprocess.py:86} INFO - Output:
[2024-12-01T00:26:39.703+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-01T00:26:39.716+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-01T00:26:39.719+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20241201T002634, start_date=20241201T002639, end_date=20241201T002639
[2024-12-01T00:26:39.735+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 123 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 2289)
[2024-12-01T00:26:39.770+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-01T00:26:39.796+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
