[2024-12-01T16:44:06.128+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T16:44:00.397703+00:00 [queued]>
[2024-12-01T16:44:06.140+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 manual__2024-12-01T16:44:00.397703+00:00 [queued]>
[2024-12-01T16:44:06.140+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T16:44:06.140+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-01T16:44:06.140+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T16:44:06.158+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-12-01 16:44:00.397703+00:00
[2024-12-01T16:44:06.162+0000] {standard_task_runner.py:55} INFO - Started process 169 to run task
[2024-12-01T16:44:06.165+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'manual__2024-12-01T16:44:00.397703+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpome957nm']
[2024-12-01T16:44:06.166+0000] {standard_task_runner.py:83} INFO - Job 208: Subtask tsk4
[2024-12-01T16:44:06.252+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 manual__2024-12-01T16:44:00.397703+00:00 [running]> on host f4e4a2d483ee
[2024-12-01T16:44:06.337+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@mailhog.local
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-12-01T16:44:00.397703+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-01T16:44:00.397703+00:00
[2024-12-01T16:44:06.338+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-01T16:44:06.339+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-12-01T16:44:06.359+0000] {subprocess.py:86} INFO - Output:
[2024-12-01T16:44:06.362+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-01T16:44:06.380+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-01T16:44:06.386+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=email_test, task_id=tsk4, execution_date=20241201T164400, start_date=20241201T164406, end_date=20241201T164406
[2024-12-01T16:44:06.411+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 208 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 169)
[2024-12-01T16:44:06.457+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-01T16:44:06.498+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
